
import 'package:flutter/material.dart';


class MyIcons extends StatelessWidget {
  

 

/* Vector Vector
    Autogenerated by FlutLab FTF Generator
  */


  IconData getIcon;
  VoidCallback pressed;
  double size;

  MyIcons(
      {Key? key, required this.getIcon, required this.pressed, this.size: 25})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return IconButton(
        icon: Icon(
          getIcon,
          color: Colors.white,
          size: size,
        ),
        onPressed: pressed);
  }
}
